site_name: Documentation for Dash sortable items
repo_url: https://github.com/WilfriedMercier/dash_sortable_items
site_author: Wilfried Mercier
site_description: Documentation for the Dash sortable items third party python library.
docs_dir: src
site_dir: ../docs
use_directory_urls: false
copyright: Copyright &copy; 2026 Mercier Wilfried
nav:
  - Getting started: index.md
  - Examples:
    - Vertical list: examples/example_vertical_list.md
    - Horizontal list: examples/example_horizontal_list.md
    - Grid layout: examples/example_grid.md
    - Locking items: examples/example_locked_items.md
    - Providing a handle: examples/example_drag_handle.md
    - Sorting sortable lists: examples/example_sorting_groups.md
    - Callback re-ordering: examples/example_callbacks.md
  - API:
    - SortableGroup: API/sortable_group.md
    - SortableItem: API/sortable_item.md
theme: 
  name: material
  logo: img/icon.png
  favicon: img/favicon.png
  icon:
    repo: fontawesome/brands/github 
  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent color: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent color: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.footer
    - navigation.path
    - navigation.expand
    - toc.follow
    - toc.integrate
    - navigation.top
    - content.code.copy
    - content.code.select
  plugins:
    - search
    - search.suggest
    - search.highlight
    - search.share
markdown_extensions:
  - tables
  - admonition
  - attr_list
  - pymdownx.inlinehilite
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      use_pygments: true
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.keys
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg